name: Trigger Netlify Build
on:
  schedule:
    - cron: "0 0 1 * *" # once a month on first day of the month: useh ttps://crontab.guru/
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5f0b641530a4b801ff6efac8
